spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: my-web
  profiles:
    active: dev
  redis:
    host: ${redis.host:192.168.200.133}
    port: ${redis.port:6379}
    lettuce:
      pool:
        enabled: true
        max-active: 10 # 最大连接数
        max-idle: 8 # 最大空闲连接数
        min-idle: 0 # 最小空闲连接数
        time-between-eviction-runs: 10s # 每10秒检查一次空闲连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host:localhost}:${db.port:3306}/${db.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}

  rabbitmq:
    host: 192.168.200.152
    port: 5672
    username: myweb
    password: myweb
    virtual-host: /myweb




knife4j:
  enable: true
  openapi:
    title: ${myweb.swagger.title:接口文档}
    description: ${myweb.swagger.desc:接口文档}
    #    email: zhanghuyi@itcast.cn
    concat: nick
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources: com.itcast.myweb.controller


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局软删除字段名
      logic-delete-value: 1       # 已删除值
      logic-not-delete-value: 0   # 未删除值

mybatis:
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    #    root: debug   全局默认级别为 debug
    com.itcast.myweb: debug




